---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: edge-processor
    app.kubernetes.io/version: 1.0.3
    app.kubernetes.io/managed-by: quarkus
  name: edge-processor
  namespace: edge 
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: edge-processor
    app.kubernetes.io/version: 1.0.3
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: edge-processor
    app.kubernetes.io/version: 1.0.3
  name: edge-processor
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edge-processor
      app.kubernetes.io/version: 1.0.3
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: edge-processor
        app.kubernetes.io/version: 1.0.3
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MQTT_URL
              value: tcp://10.43.235.251:1883
          image: quay.io/dbrugger946/iot-processor-edge:1.0.3
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: edge-processor
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
